name: flutter_context_dtx
description: A package that simplifies the access most of used properties/functions right in the BuildContext.
version: 1.3.0
repository: https://github.com/zambiee/dtx/flutter/flutter_context_dtx
issue_tracker: https://github.com/zambiee/dtx/flutter/flutter_context_dtx/issues
homepage: https://github.com/zambiee/flutter/dtx/flutter_context_dtx
documentation: https://github.com/zambiee/dtx/flutter/flutter_context_dtx

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:  
  flutter_test:
    sdk: flutter
  lint: ^1.5.1