name: shared_preferences_dtx
description: A package that simplifies the access most of used properties/functions right in the package shared_preferences.
version: 1.0.0
authors:  
  - "Zambiee"
repository: https://github.com/zambiee/dtx/other_packages/shared_preferences_dtx
issue_tracker: https://github.com/zambiee/dtx/other_packages/shared_preferences_dtx/issues
homepage: https://github.com/zambiee/dtx/other_packages/shared_preferences_dtx
documentation: https://github.com/zambiee/dtx/other_packages/shared_preferences_dtx

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  shared_preferences: ^0.5.12+4
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
